import type {
  FoodAndSuppliesMonthly,
  HealthcareCostFactors,
  HousingDifferential,
  StageMonthlyBreakdown,
  StageMonthlyCosts,
} from "@/types/parenting";

/**
 * Expansion metros scaled from a curated peer seed.
 * Indexes are illustrative planning factors (not live quotes).
 */
export type MetroExpansion = {
  locationId: string;
  displayName: string;
  state: string;
  stateCode: string;
  /** Peer `locationId` already defined as a full hand-tuned seed. */
  peerId: string;
  /** Uniform scale on stage childcare line items. */
  childcareScale: number;
  /** Scale on rents / family home quotes. */
  housingScale: number;
  /** Scale on premiums + OOP healthcare. */
  healthcareScale: number;
  /** Scale on food / supplies anchors and stage food/supplies. */
  foodScale: number;
  tenure?: HousingDifferential["tenure"];
};

export const METRO_EXPANSIONS: MetroExpansion[] = [
  {
    locationId: "san-diego",
    displayName: "San Diego, CA",
    state: "CA",
    stateCode: "CA",
    peerId: "los-angeles",
    childcareScale: 0.92,
    housingScale: 0.88,
    healthcareScale: 0.95,
    foodScale: 0.96,
    tenure: "mixed",
  },
  {
    locationId: "san-jose",
    displayName: "San Jose, CA",
    state: "CA",
    stateCode: "CA",
    peerId: "san-francisco",
    childcareScale: 0.9,
    housingScale: 0.82,
    healthcareScale: 0.94,
    foodScale: 0.92,
    tenure: "mortgage",
  },
  {
    locationId: "sacramento",
    displayName: "Sacramento, CA",
    state: "CA",
    stateCode: "CA",
    peerId: "los-angeles",
    childcareScale: 0.72,
    housingScale: 0.62,
    healthcareScale: 0.88,
    foodScale: 0.85,
    tenure: "mortgage",
  },
  {
    locationId: "houston",
    displayName: "Houston, TX",
    state: "TX",
    stateCode: "TX",
    peerId: "dallas",
    childcareScale: 0.98,
    housingScale: 0.96,
    healthcareScale: 0.98,
    foodScale: 0.97,
    tenure: "mortgage",
  },
  {
    locationId: "san-antonio",
    displayName: "San Antonio, TX",
    state: "TX",
    stateCode: "TX",
    peerId: "dallas",
    childcareScale: 0.88,
    housingScale: 0.85,
    healthcareScale: 0.92,
    foodScale: 0.9,
    tenure: "mortgage",
  },
  {
    locationId: "philadelphia",
    displayName: "Philadelphia, PA",
    state: "PA",
    stateCode: "PA",
    peerId: "chicago",
    childcareScale: 1.08,
    housingScale: 1.05,
    healthcareScale: 1.06,
    foodScale: 1.05,
    tenure: "mixed",
  },
  {
    locationId: "pittsburgh",
    displayName: "Pittsburgh, PA",
    state: "PA",
    stateCode: "PA",
    peerId: "chicago",
    childcareScale: 0.88,
    housingScale: 0.78,
    healthcareScale: 0.94,
    foodScale: 0.92,
    tenure: "mixed",
  },
  {
    locationId: "portland",
    displayName: "Portland, OR",
    state: "OR",
    stateCode: "OR",
    peerId: "seattle",
    childcareScale: 0.86,
    housingScale: 0.82,
    healthcareScale: 0.92,
    foodScale: 0.9,
    tenure: "mixed",
  },
  {
    locationId: "bend",
    displayName: "Bend, OR",
    state: "OR",
    stateCode: "OR",
    peerId: "seattle",
    childcareScale: 0.78,
    housingScale: 0.88,
    healthcareScale: 0.9,
    foodScale: 0.92,
    tenure: "mortgage",
  },
  {
    locationId: "nashville",
    displayName: "Nashville, TN",
    state: "TN",
    stateCode: "TN",
    peerId: "atlanta",
    childcareScale: 1.06,
    housingScale: 1.12,
    healthcareScale: 1.02,
    foodScale: 1.04,
    tenure: "mixed",
  },
  {
    locationId: "memphis",
    displayName: "Memphis, TN",
    state: "TN",
    stateCode: "TN",
    peerId: "atlanta",
    childcareScale: 0.82,
    housingScale: 0.72,
    healthcareScale: 0.9,
    foodScale: 0.88,
    tenure: "mortgage",
  },
  {
    locationId: "charlotte",
    displayName: "Charlotte, NC",
    state: "NC",
    stateCode: "NC",
    peerId: "atlanta",
    childcareScale: 1.02,
    housingScale: 1.05,
    healthcareScale: 1.0,
    foodScale: 1.02,
    tenure: "mortgage",
  },
  {
    locationId: "raleigh",
    displayName: "Raleigh, NC",
    state: "NC",
    stateCode: "NC",
    peerId: "atlanta",
    childcareScale: 0.98,
    housingScale: 1.0,
    healthcareScale: 0.98,
    foodScale: 0.98,
    tenure: "mortgage",
  },
  {
    locationId: "asheville",
    displayName: "Asheville, NC",
    state: "NC",
    stateCode: "NC",
    peerId: "atlanta",
    childcareScale: 0.92,
    housingScale: 0.98,
    healthcareScale: 0.95,
    foodScale: 0.96,
    tenure: "mixed",
  },
  {
    locationId: "minneapolis",
    displayName: "Minneapolis, MN",
    state: "MN",
    stateCode: "MN",
    peerId: "chicago",
    childcareScale: 1.06,
    housingScale: 1.02,
    healthcareScale: 1.04,
    foodScale: 1.05,
    tenure: "mixed",
  },
  {
    locationId: "detroit",
    displayName: "Detroit, MI",
    state: "MI",
    stateCode: "MI",
    peerId: "chicago",
    childcareScale: 0.82,
    housingScale: 0.68,
    healthcareScale: 0.92,
    foodScale: 0.88,
    tenure: "mixed",
  },
  {
    locationId: "ann-arbor",
    displayName: "Ann Arbor, MI",
    state: "MI",
    stateCode: "MI",
    peerId: "chicago",
    childcareScale: 1.05,
    housingScale: 1.08,
    healthcareScale: 1.02,
    foodScale: 1.04,
    tenure: "mixed",
  },
  {
    locationId: "orlando",
    displayName: "Orlando, FL",
    state: "FL",
    stateCode: "FL",
    peerId: "miami",
    childcareScale: 0.82,
    housingScale: 0.72,
    healthcareScale: 0.9,
    foodScale: 0.88,
    tenure: "mortgage",
  },
  {
    locationId: "tampa",
    displayName: "Tampa, FL",
    state: "FL",
    stateCode: "FL",
    peerId: "miami",
    childcareScale: 0.85,
    housingScale: 0.78,
    healthcareScale: 0.92,
    foodScale: 0.9,
    tenure: "mixed",
  },
  {
    locationId: "fort-lauderdale",
    displayName: "Fort Lauderdale, FL",
    state: "FL",
    stateCode: "FL",
    peerId: "miami",
    childcareScale: 0.95,
    housingScale: 0.92,
    healthcareScale: 0.98,
    foodScale: 0.96,
    tenure: "rent",
  },
  {
    locationId: "las-vegas",
    displayName: "Las Vegas, NV",
    state: "NV",
    stateCode: "NV",
    peerId: "phoenix",
    childcareScale: 1.05,
    housingScale: 1.08,
    healthcareScale: 1.02,
    foodScale: 1.04,
    tenure: "mortgage",
  },
  {
    locationId: "salt-lake-city",
    displayName: "Salt Lake City, UT",
    state: "UT",
    stateCode: "UT",
    peerId: "denver",
    childcareScale: 0.9,
    housingScale: 0.88,
    healthcareScale: 0.94,
    foodScale: 0.92,
    tenure: "mortgage",
  },
  {
    locationId: "kansas-city",
    displayName: "Kansas City, MO",
    state: "MO",
    stateCode: "MO",
    peerId: "dallas",
    childcareScale: 0.95,
    housingScale: 0.9,
    healthcareScale: 0.96,
    foodScale: 0.94,
    tenure: "mortgage",
  },
  {
    locationId: "st-louis",
    displayName: "St. Louis, MO",
    state: "MO",
    stateCode: "MO",
    peerId: "chicago",
    childcareScale: 0.86,
    housingScale: 0.75,
    healthcareScale: 0.94,
    foodScale: 0.9,
    tenure: "mixed",
  },
  {
    locationId: "cleveland",
    displayName: "Cleveland, OH",
    state: "OH",
    stateCode: "OH",
    peerId: "chicago",
    childcareScale: 0.8,
    housingScale: 0.7,
    healthcareScale: 0.92,
    foodScale: 0.88,
    tenure: "mixed",
  },
  {
    locationId: "cincinnati",
    displayName: "Cincinnati, OH",
    state: "OH",
    stateCode: "OH",
    peerId: "chicago",
    childcareScale: 0.86,
    housingScale: 0.78,
    healthcareScale: 0.94,
    foodScale: 0.9,
    tenure: "mortgage",
  },
  {
    locationId: "columbus",
    displayName: "Columbus, OH",
    state: "OH",
    stateCode: "OH",
    peerId: "chicago",
    childcareScale: 0.9,
    housingScale: 0.85,
    healthcareScale: 0.95,
    foodScale: 0.92,
    tenure: "mortgage",
  },
  {
    locationId: "indianapolis",
    displayName: "Indianapolis, IN",
    state: "IN",
    stateCode: "IN",
    peerId: "chicago",
    childcareScale: 0.84,
    housingScale: 0.76,
    healthcareScale: 0.92,
    foodScale: 0.88,
    tenure: "mortgage",
  },
  {
    locationId: "milwaukee",
    displayName: "Milwaukee, WI",
    state: "WI",
    stateCode: "WI",
    peerId: "chicago",
    childcareScale: 0.92,
    housingScale: 0.82,
    healthcareScale: 0.96,
    foodScale: 0.94,
    tenure: "mixed",
  },
  {
    locationId: "madison",
    displayName: "Madison, WI",
    state: "WI",
    stateCode: "WI",
    peerId: "chicago",
    childcareScale: 0.98,
    housingScale: 0.95,
    healthcareScale: 0.98,
    foodScale: 0.98,
    tenure: "mixed",
  },
  {
    locationId: "baltimore",
    displayName: "Baltimore, MD",
    state: "MD",
    stateCode: "MD",
    peerId: "chicago",
    childcareScale: 1.08,
    housingScale: 1.02,
    healthcareScale: 1.06,
    foodScale: 1.04,
    tenure: "mixed",
  },
  {
    locationId: "washington",
    displayName: "Washington, DC",
    state: "DC",
    stateCode: "DC",
    peerId: "boston",
    childcareScale: 1.05,
    housingScale: 1.08,
    healthcareScale: 1.04,
    foodScale: 1.02,
    tenure: "rent",
  },
  {
    locationId: "oklahoma-city",
    displayName: "Oklahoma City, OK",
    state: "OK",
    stateCode: "OK",
    peerId: "dallas",
    childcareScale: 0.82,
    housingScale: 0.78,
    healthcareScale: 0.9,
    foodScale: 0.86,
    tenure: "mortgage",
  },
  {
    locationId: "louisville",
    displayName: "Louisville, KY",
    state: "KY",
    stateCode: "KY",
    peerId: "atlanta",
    childcareScale: 0.86,
    housingScale: 0.8,
    healthcareScale: 0.92,
    foodScale: 0.9,
    tenure: "mortgage",
  },
  {
    locationId: "richmond",
    displayName: "Richmond, VA",
    state: "VA",
    stateCode: "VA",
    peerId: "atlanta",
    childcareScale: 0.96,
    housingScale: 0.95,
    healthcareScale: 0.98,
    foodScale: 0.96,
    tenure: "mixed",
  },
  {
    locationId: "boise",
    displayName: "Boise, ID",
    state: "ID",
    stateCode: "ID",
    peerId: "denver",
    childcareScale: 0.88,
    housingScale: 0.92,
    healthcareScale: 0.92,
    foodScale: 0.9,
    tenure: "mortgage",
  },
  {
    locationId: "albuquerque",
    displayName: "Albuquerque, NM",
    state: "NM",
    stateCode: "NM",
    peerId: "phoenix",
    childcareScale: 0.9,
    housingScale: 0.85,
    healthcareScale: 0.94,
    foodScale: 0.92,
    tenure: "mortgage",
  },
  {
    locationId: "santa-fe",
    displayName: "Santa Fe, NM",
    state: "NM",
    stateCode: "NM",
    peerId: "denver",
    childcareScale: 0.92,
    housingScale: 1.05,
    healthcareScale: 0.96,
    foodScale: 0.98,
    tenure: "mixed",
  },
  {
    locationId: "tucson",
    displayName: "Tucson, AZ",
    state: "AZ",
    stateCode: "AZ",
    peerId: "phoenix",
    childcareScale: 0.88,
    housingScale: 0.82,
    healthcareScale: 0.92,
    foodScale: 0.9,
    tenure: "mortgage",
  },
  {
    locationId: "scottsdale",
    displayName: "Scottsdale, AZ",
    state: "AZ",
    stateCode: "AZ",
    peerId: "phoenix",
    childcareScale: 1.18,
    housingScale: 1.35,
    healthcareScale: 1.08,
    foodScale: 1.12,
    tenure: "mortgage",
  },
  {
    locationId: "honolulu",
    displayName: "Honolulu, HI",
    state: "HI",
    stateCode: "HI",
    peerId: "san-francisco",
    childcareScale: 0.88,
    housingScale: 0.78,
    healthcareScale: 1.05,
    foodScale: 1.15,
    tenure: "rent",
  },
  {
    locationId: "anchorage",
    displayName: "Anchorage, AK",
    state: "AK",
    stateCode: "AK",
    peerId: "seattle",
    childcareScale: 0.92,
    housingScale: 0.85,
    healthcareScale: 1.08,
    foodScale: 1.2,
    tenure: "mixed",
  },
  {
    locationId: "bozeman",
    displayName: "Bozeman, MT",
    state: "MT",
    stateCode: "MT",
    peerId: "denver",
    childcareScale: 0.95,
    housingScale: 1.12,
    healthcareScale: 0.98,
    foodScale: 1.05,
    tenure: "mortgage",
  },
  {
    locationId: "charleston",
    displayName: "Charleston, SC",
    state: "SC",
    stateCode: "SC",
    peerId: "atlanta",
    childcareScale: 1.0,
    housingScale: 1.08,
    healthcareScale: 0.98,
    foodScale: 1.02,
    tenure: "mixed",
  },
  {
    locationId: "savannah",
    displayName: "Savannah, GA",
    state: "GA",
    stateCode: "GA",
    peerId: "atlanta",
    childcareScale: 0.9,
    housingScale: 0.92,
    healthcareScale: 0.94,
    foodScale: 0.94,
    tenure: "mixed",
  },
  {
    locationId: "boulder",
    displayName: "Boulder, CO",
    state: "CO",
    stateCode: "CO",
    peerId: "denver",
    childcareScale: 1.15,
    housingScale: 1.28,
    healthcareScale: 1.06,
    foodScale: 1.1,
    tenure: "mortgage",
  },
  {
    locationId: "jersey-city",
    displayName: "Jersey City, NJ",
    state: "NJ",
    stateCode: "NJ",
    peerId: "new-york",
    childcareScale: 0.82,
    housingScale: 0.68,
    healthcareScale: 0.95,
    foodScale: 0.9,
    tenure: "rent",
  },
  {
    locationId: "brooklyn",
    displayName: "Brooklyn, NY",
    state: "NY",
    stateCode: "NY",
    peerId: "new-york",
    childcareScale: 0.92,
    housingScale: 0.85,
    healthcareScale: 0.98,
    foodScale: 0.95,
    tenure: "rent",
  },
];

function roundMoney(value: number): number {
  return Math.round(value * 100) / 100;
}

function scaleStage(
  s: StageMonthlyBreakdown,
  childcareScale: number,
  foodScale: number,
  healthcareScale: number,
): StageMonthlyBreakdown {
  return {
    childcare: roundMoney(s.childcare * childcareScale),
    food: roundMoney(s.food * foodScale),
    supplies: roundMoney(s.supplies * foodScale),
    healthcare: roundMoney(s.healthcare * healthcareScale),
    other: roundMoney(s.other * ((childcareScale + foodScale) / 2)),
  };
}

export type ScalableCitySeed = {
  locationId: string;
  displayName: string;
  state: string;
  stateCode: string;
  updatedAt?: string;
  stageMonthly: StageMonthlyCosts;
  housing: Omit<HousingDifferential, "familyPremiumMonthly"> & {
    familyPremiumMonthly?: number;
  };
  healthcare: HealthcareCostFactors;
  foodAndSupplies: FoodAndSuppliesMonthly;
};

/**
 * Builds a full city seed by scaling a hand-tuned peer metro.
 */
export function expandMetroFromPeer(
  peer: ScalableCitySeed,
  expansion: MetroExpansion,
): ScalableCitySeed {
  const { childcareScale, housingScale, healthcareScale, foodScale } = expansion;

  return {
    locationId: expansion.locationId,
    displayName: expansion.displayName,
    state: expansion.state,
    stateCode: expansion.stateCode,
    stageMonthly: {
      infant: scaleStage(
        peer.stageMonthly.infant,
        childcareScale,
        foodScale,
        healthcareScale,
      ),
      toddler: scaleStage(
        peer.stageMonthly.toddler,
        childcareScale,
        foodScale,
        healthcareScale,
      ),
      schoolAge: scaleStage(
        peer.stageMonthly.schoolAge,
        childcareScale,
        foodScale,
        healthcareScale,
      ),
    },
    housing: {
      avgRent1to2Bed: roundMoney(peer.housing.avgRent1to2Bed * housingScale),
      avgFamilyHome3Plus: roundMoney(
        peer.housing.avgFamilyHome3Plus * housingScale,
      ),
      tenure: expansion.tenure ?? peer.housing.tenure,
    },
    healthcare: {
      employerFamilyPremiumMonthly: roundMoney(
        peer.healthcare.employerFamilyPremiumMonthly * healthcareScale,
      ),
      marketplaceFamilyPremiumMonthly: roundMoney(
        peer.healthcare.marketplaceFamilyPremiumMonthly * healthcareScale,
      ),
      outOfPocketPerChildMonthly: roundMoney(
        peer.healthcare.outOfPocketPerChildMonthly * healthcareScale,
      ),
      dentalVisionMonthly: roundMoney(
        peer.healthcare.dentalVisionMonthly * healthcareScale,
      ),
      regionalIndex: roundMoney(
        peer.healthcare.regionalIndex *
          ((healthcareScale + housingScale) / 2),
      ),
    },
    foodAndSupplies: {
      foodPerChild: roundMoney(peer.foodAndSupplies.foodPerChild * foodScale),
      diapersAndWipes: roundMoney(
        peer.foodAndSupplies.diapersAndWipes * foodScale,
      ),
      formulaOrBabyFood: roundMoney(
        peer.foodAndSupplies.formulaOrBabyFood * foodScale,
      ),
      householdSupplies: roundMoney(
        peer.foodAndSupplies.householdSupplies * foodScale,
      ),
    },
  };
}
